server:
  port: 10200 # 服务端口号
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/
            
spring:  
    application:
        name: demo-service # 注册到注册中心的服务名称