server:
  port: 13000
  
spring:
    application:
        name: demo-order-client
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:11000/eureka/
            
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000